/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Atif Jalal
 */
public class InsertRecipe extends javax.swing.JFrame {

    /**
     * Creates new form InsertRecipe
     */
    public InsertRecipe() {
        initComponents();

    }

    public InsertRecipe(String username,String ID) {
        initComponents();
        imagelabel.setText("");
        userid.setText(ID);
        this.username.setText(username);
        setLocationRelativeTo(null);
        closeicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
        minimizeicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
        backbutton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        selectedimagename.setText("");
        jSeparator2.setOpaque(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Clases.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        recipename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ing1 = new javax.swing.JComboBox<String>();
        ing2 = new javax.swing.JComboBox<String>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ing3 = new javax.swing.JComboBox<String>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        serves = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Recipemethod = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        cookingtime = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        calories = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        addrecipebutton = new javax.swing.JButton();
        uploadrecipeimage = new javax.swing.JButton();
        panelRound2 = new Clases.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        closeicon = new javax.swing.JLabel();
        minimizeicon = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        imagelabel = new javax.swing.JLabel();
        selectedimagename = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        additionaling = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        panelRound1.setBackground(new java.awt.Color(196, 181, 129));

        jLabel3.setBackground(new java.awt.Color(196, 181, 129));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Enter name:");

        recipename.setBackground(new java.awt.Color(196, 181, 129));
        recipename.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recipename.setForeground(new java.awt.Color(0, 51, 51));
        recipename.setBorder(null);

        jLabel5.setBackground(new java.awt.Color(196, 181, 129));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Choose Ingredients:");

        jLabel6.setBackground(new java.awt.Color(196, 181, 129));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("1st Ingredient:");

        ing1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "onion", "potato", "tomato", "carrot", "bell Pepper", "lemon", "mango", "banana", "apple", "orange", "milk", "egg", "bread", "cheese", "cream", "butter", "chocolate", "almond", "walnut", "chicken", "mutton", "beef", "fish", "prawns", "spaghetti" }));

        ing2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mango", "onion", "potato", "tomato", "carrot", "bell Pepper", "lemon", "banana", "apple", "orange", "milk", "egg", "bread", "cheese", "cream", "butter", "chocolate", "almond", "walnut", "chicken", "mutton", "beef", "fish", "prawns", "spaghetti" }));

        jLabel7.setBackground(new java.awt.Color(196, 181, 129));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("2nd Ingredient:");

        jLabel8.setBackground(new java.awt.Color(196, 181, 129));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("3rd Ingredient:");

        ing3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "chicken", "mango", "onion", "potato", "tomato", "carrot", "bell Pepper", "lemon", "banana", "apple", "orange", "milk", "egg", "bread", "cheese", "cream", "butter", "chocolate", "almond", "walnut", "chicken", "mutton", "beef", "fish", "prawns", "spaghetti" }));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));

        jLabel9.setBackground(new java.awt.Color(196, 181, 129));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Choose Serves:");

        serves.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        jLabel10.setBackground(new java.awt.Color(196, 181, 129));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Write recipe Method:");

        Recipemethod.setColumns(20);
        Recipemethod.setRows(5);
        jScrollPane1.setViewportView(Recipemethod);

        jLabel11.setBackground(new java.awt.Color(196, 181, 129));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Enter cooking time:");

        cookingtime.setBackground(new java.awt.Color(196, 181, 129));
        cookingtime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cookingtime.setForeground(new java.awt.Color(0, 51, 51));
        cookingtime.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 51));
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 3));

        calories.setBackground(new java.awt.Color(196, 181, 129));
        calories.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calories.setForeground(new java.awt.Color(0, 51, 51));
        calories.setBorder(null);

        jLabel12.setBackground(new java.awt.Color(196, 181, 129));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Enter calories:");

        jSeparator3.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 51));

        addrecipebutton.setBackground(new java.awt.Color(0, 51, 51));
        addrecipebutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addrecipebutton.setForeground(new java.awt.Color(196, 181, 129));
        addrecipebutton.setText("Add");
        addrecipebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrecipebuttonActionPerformed(evt);
            }
        });

        uploadrecipeimage.setBackground(new java.awt.Color(0, 51, 51));
        uploadrecipeimage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        uploadrecipeimage.setForeground(new java.awt.Color(196, 181, 129));
        uploadrecipeimage.setText("Upload");
        uploadrecipeimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadrecipeimageActionPerformed(evt);
            }
        });

        panelRound2.setBackground(new java.awt.Color(0, 51, 51));
        panelRound2.setForeground(new java.awt.Color(0, 51, 51));

        jLabel4.setBackground(new java.awt.Color(196, 181, 129));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(196, 181, 129));
        jLabel4.setText("Add Recipe");

        closeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/closegold.png"))); // NOI18N
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
        });

        minimizeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/minimizegold.png"))); // NOI18N
        minimizeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeiconMouseClicked(evt);
            }
        });

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/backbuttongold.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });

        username.setForeground(new java.awt.Color(0, 51, 51));
        username.setText("jLabel1");

        userid.setForeground(new java.awt.Color(0, 51, 51));
        userid.setText("jLabel1");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backbutton)
                .addGap(32, 32, 32)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userid)
                .addGap(306, 306, 306)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeicon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeicon)
                .addGap(18, 18, 18))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(username)
                        .addComponent(userid))
                    .addComponent(closeicon)
                    .addComponent(minimizeicon)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(backbutton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 255));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(208, 212));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(208, 212));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(400, 400));

        imagelabel.setBackground(new java.awt.Color(255, 51, 0));
        imagelabel.setForeground(new java.awt.Color(255, 0, 0));
        imagelabel.setText("image");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(imagelabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        selectedimagename.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        selectedimagename.setForeground(new java.awt.Color(0, 51, 51));
        selectedimagename.setText("imagename");

        jLabel13.setBackground(new java.awt.Color(196, 181, 129));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Additional Ingredients:");

        additionaling.setColumns(20);
        additionaling.setRows(5);
        jScrollPane2.setViewportView(additionaling);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addrecipebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound1Layout.createSequentialGroup()
                                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(serves, 0, 336, Short.MAX_VALUE)
                                            .addComponent(recipename)
                                            .addGroup(panelRound1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelRound1Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ing2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(panelRound1Layout.createSequentialGroup()
                                                        .addGap(3, 3, 3)
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ing3, 0, 183, Short.MAX_VALUE))
                                                    .addGroup(panelRound1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(23, 23, 23)
                                                        .addComponent(ing1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addComponent(jSeparator1))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11)
                                            .addComponent(cookingtime)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                            .addComponent(calories)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jScrollPane2)))
                                    .addGroup(panelRound1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(272, 272, 272))
                                    .addComponent(jScrollPane1))
                                .addGap(27, 27, 27)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(uploadrecipeimage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectedimagename)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recipename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(ing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel11)
                                .addGap(3, 3, 3)
                                .addComponent(cookingtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ing2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(21, 21, 21)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ing3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serves, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadrecipeimage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedimagename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addrecipebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(panelRound1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadrecipeimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadrecipeimageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        imagelabel.setIcon(new ImageIcon(f.toString()));
        filename = f.getAbsolutePath();
        selectedimagename.setText(filename);

    }//GEN-LAST:event_uploadrecipeimageActionPerformed

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeiconMouseClicked

    private void minimizeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeiconMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeiconMouseClicked

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
        String username = this.username.getText();
        String Id=userid.getText();
        adminDashboard ad = new adminDashboard(username,Id);
        ad.show();
        dispose();
    }//GEN-LAST:event_backbuttonMouseClicked

    private void addrecipebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrecipebuttonActionPerformed
        // TODO add your handling code here:

        String rname = recipename.getText();
        int rcookingtime = Integer.parseInt(cookingtime.getText());
        double rcalories = Double.parseDouble(calories.getText());
        String ingredient1 = (String) ing1.getSelectedItem();
        String ingredient2 = (String) ing2.getSelectedItem();
        String ingredient3 = (String) ing3.getSelectedItem();
        int rserves = Integer.parseInt((String) serves.getSelectedItem());
        String rmethod = Recipemethod.getText();
        String adding=additionaling.getText();
        String imagepaath=selectedimagename.getText();

        String uname=username.getText();
        String Id=userid.getText();
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        String databasepath = "Database.accdb";
        try {

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://" + databasepath);
            FileInputStream input = new FileInputStream(imagepaath);
            String query = "INSERT INTO recipes (Name, Ingredient1, Ingredient2, Ingredient3, Serves, CookingTime, Calories, Method,RecipeImage, AdditionalIngredients,ImageAddress) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(query);
            pst.setString(1, rname);
            pst.setString(2, ingredient1);
            pst.setString(3, ingredient2);
            pst.setString(4, ingredient3);
            pst.setInt(5, rserves);
            pst.setInt(6, rcookingtime);
            pst.setDouble(7, rcalories);
            pst.setString(8, rmethod);
            pst.setBinaryStream(9, input);
            pst.setString(10, adding);
            pst.setString(11, imagepaath);
            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Recipe Added");
                adminDashboard ad=new adminDashboard(uname, Id);
                
                ad.show();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "something wen wrong");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_addrecipebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertRecipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Recipemethod;
    private javax.swing.JTextArea additionaling;
    private javax.swing.JButton addrecipebutton;
    private javax.swing.JLabel backbutton;
    private javax.swing.JTextField calories;
    private javax.swing.JLabel closeicon;
    private javax.swing.JTextField cookingtime;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JComboBox<String> ing1;
    private javax.swing.JComboBox<String> ing2;
    private javax.swing.JComboBox<String> ing3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel minimizeicon;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound2;
    private javax.swing.JTextField recipename;
    private javax.swing.JLabel selectedimagename;
    private javax.swing.JComboBox<String> serves;
    private javax.swing.JButton uploadrecipeimage;
    private javax.swing.JLabel userid;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
    byte[] photo = null;
    String filename = null;
}
