/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class LoginForm extends javax.swing.JFrame {
String databasepath="Database.accdb";
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setBackground (new Color (0.0f, 0.0f, 0.0f, 0.0f));
        loginerror.setText("");
        setLocationRelativeTo(null);
        closeicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
        minimizeicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
        signup.setCursor(new Cursor(Cursor.HAND_CURSOR));
        forgotpassword.setCursor(new Cursor(Cursor.HAND_CURSOR));
        loginbutton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        ///////kindly remove this after completing
      inputemail.setText("mairaawan90@gmail.com");
        inputPassword.setText("09876543");
        
        inputemail.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                loginerror.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                loginerror.setText("");
            }
        });
        inputPassword.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                loginerror.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                loginerror.setText("");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Clases.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        inputemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        forgotpassword = new javax.swing.JLabel();
        loginerror = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        closeicon = new javax.swing.JLabel();
        minimizeicon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelRound3 = new Clases.PanelRound();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(0, 51, 51));
        panelRound1.setPreferredSize(new java.awt.Dimension(285, 595));
        panelRound1.setRoundBottomLeft(0);
        panelRound1.setRoundBottomRight(100);
        panelRound1.setRoundTopLeft(0);
        panelRound1.setRoundTopRight(100);

        jLabel1.setBackground(new java.awt.Color(196, 181, 129));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(196, 181, 129));
        jLabel1.setText("Email Address:");

        inputemail.setBackground(new java.awt.Color(0, 51, 51));
        inputemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputemail.setForeground(new java.awt.Color(196, 181, 129));
        inputemail.setBorder(null);
        inputemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputemailActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(196, 181, 129));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(196, 181, 129));
        jLabel2.setText("Password:");

        inputPassword.setBackground(new java.awt.Color(0, 51, 51));
        inputPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputPassword.setForeground(new java.awt.Color(196, 181, 129));
        inputPassword.setBorder(null);

        forgotpassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forgotpassword.setForeground(new java.awt.Color(51, 153, 255));
        forgotpassword.setText("Forgot Password?");
        forgotpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpasswordMouseClicked(evt);
            }
        });

        loginerror.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginerror.setForeground(new java.awt.Color(255, 0, 0));
        loginerror.setText("login error!");

        loginbutton.setBackground(new java.awt.Color(196, 181, 129));
        loginbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(0, 51, 51));
        loginbutton.setText("login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(196, 181, 129));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(196, 181, 129));
        jLabel3.setText("Don't have an account?");

        signup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signup.setForeground(new java.awt.Color(51, 153, 255));
        signup.setText("Signup");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(196, 181, 129));
        jSeparator1.setForeground(new java.awt.Color(196, 181, 129));
        jSeparator1.setAutoscrolls(true);

        jSeparator2.setBackground(new java.awt.Color(196, 181, 129));
        jSeparator2.setForeground(new java.awt.Color(196, 181, 129));

        closeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/closegold.png"))); // NOI18N
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
        });

        minimizeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/minimizegold.png"))); // NOI18N
        minimizeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeiconMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(minimizeicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeicon))
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forgotpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputemail, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                        .addComponent(jSeparator1)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputPassword)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(loginerror)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRound1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(signup))
                                    .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(94, 94, 94))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeicon)
                    .addComponent(closeicon))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forgotpassword)
                .addGap(23, 23, 23)
                .addComponent(loginerror)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(signup))
                .addGap(41, 41, 41))
        );

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, 540));

        panelRound3.setBackground(new java.awt.Color(255, 204, 204));
        panelRound3.setRoundBottomLeft(100);
        panelRound3.setRoundBottomRight(0);
        panelRound3.setRoundTopLeft(100);
        panelRound3.setRoundTopRight(0);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/login.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        panelRound3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        getContentPane().add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 570, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgotpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordMouseClicked
        // TODO add your handling code here:
        forgotpassword fp = new forgotpassword();
        fp.show();
        dispose();
    }//GEN-LAST:event_forgotpasswordMouseClicked

    public String encryptPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(password.getBytes());
            byte[] digest = md.digest();
            StringBuilder sb = new StringBuilder();
            for (byte b : digest) {
                sb.append(String.format("%02x", b & 0xff));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
            return null;
        }
    }
    
    
    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
        String emailaddress = inputemail.getText();
        String password = new String(inputPassword.getPassword());
        String admin = "admin";
        String user = "user";

        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        String encryptedPassword = encryptPassword(password);

        if (emailaddress.isEmpty() && password.isEmpty()) {
            loginerror.setText("Fields cannot be empty");
        } else if (emailaddress.isEmpty()) {
            loginerror.setText("Username cannot be empty");
        } else if (password.isEmpty()) {
            loginerror.setText("Password cannot be empty");
        } else {

            try {

                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://" + databasepath);
                
                String query = "select * from user where Email='" + emailaddress + "' and Password='" + encryptedPassword + "'";
                pst = con.prepareStatement(query);
                rs = pst.executeQuery();

                if (rs.next()) {

                    JOptionPane.showMessageDialog(this, "Login Successful");
                    String usert = rs.getString("usertype");
                    String username = rs.getString("Username");
                    String userId = rs.getString("ID");
                    if (usert.equals(admin)) {
                        adminDashboard ad = new adminDashboard(username,userId);
                        ad.show();
                        dispose();
                    }
                    else if (usert.equals(user)) {

                        UserDashboard ud =new UserDashboard(username,userId);
                        ud.show();
                        dispose();
                    }

                } else {

                    loginerror.setText("Username or Password is Incorrect");
                    inputemail.setText("");
                    inputPassword.setText("");
                }

            } catch (HeadlessException | SQLException e) {
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        // TODO add your handling code here:
        Signup su=new Signup();
        su.show();
        dispose();
    }//GEN-LAST:event_signupMouseClicked

    private void inputemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputemailActionPerformed

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeiconMouseClicked

    private void minimizeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeiconMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeiconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeicon;
    private javax.swing.JLabel forgotpassword;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputemail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel loginerror;
    private javax.swing.JLabel minimizeicon;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound3;
    private javax.swing.JLabel signup;
    // End of variables declaration//GEN-END:variables
}
