/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.awt.Cursor;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author Atif Jalal
 */
public class searchfilter extends javax.swing.JFrame {

    String databasepath = "Database.accdb";
    /**
     * Creates new form searchfilter
     */
    DefaultListModel jlistOneModel, jlistTwoModel;
//    String str[] = {"egg", "milk", "cream", "chocolate", "potato", "tomato", "carrot"};
    String str[] = {"egg", "milk", "choclate", "onion", "potato", "tomato", "carrot", "bell pepper",
        "lemon",
        "chicken",
        "mutton",
        "beaf",
        "fish",
        "prawns",
        "bread",
        "cheese",
        "cream",
        "butter",
        "almond",
        "wallnet",
        "spaghetti",
        "banana",
        "apple",
        "orange"};

    public searchfilter() {
        initComponents();
        setLocationRelativeTo(null);

    }

    public searchfilter(String name, String id) {
        initComponents();
        setLocationRelativeTo(null);

        userid.setText(id);
        username.setText(name);

        closeicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
        minimizeicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
        backbutton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));

        jlistOneModel = new DefaultListModel();
        jlistTwoModel = new DefaultListModel();
        recipiefound.setText("");
        gotorecipies.setText("");
        for (int i = 0; i < str.length; i++) {
            jlistOneModel.addElement(str[i]);
        }
        jListOne.setModel(jlistOneModel);
        gotorecipies.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Clases.PanelRound();
        recipiefound = new javax.swing.JLabel();
        gotorecipies = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minimizeicon = new javax.swing.JLabel();
        closeicon = new javax.swing.JLabel();
        panelRound2 = new Clases.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListOne = new javax.swing.JList<String>();
        btnSingleRight = new javax.swing.JButton();
        panelRound3 = new Clases.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTwo = new javax.swing.JList<String>();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        userid = new javax.swing.JLabel();
        username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setBackground(new java.awt.Color(196, 181, 129));

        recipiefound.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recipiefound.setForeground(new java.awt.Color(0, 51, 51));
        recipiefound.setText("found");

        gotorecipies.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gotorecipies.setForeground(new java.awt.Color(51, 153, 255));
        gotorecipies.setText("gotorecipies");
        gotorecipies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotorecipiesMouseClicked(evt);
            }
        });

        searchbutton.setBackground(new java.awt.Color(0, 51, 51));
        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(196, 181, 129));
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/backbuttongreen.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(196, 181, 129));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Search Recipe");

        minimizeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/minimizegreen.png"))); // NOI18N
        minimizeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeiconMouseClicked(evt);
            }
        });

        closeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/closegreen.png"))); // NOI18N
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
        });

        panelRound2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(196, 181, 129));
        jLabel1.setText("Available Incredient");

        jListOne.setBackground(new java.awt.Color(196, 181, 129));
        jListOne.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jListOne.setForeground(new java.awt.Color(0, 51, 51));
        jScrollPane1.setViewportView(jListOne);

        btnSingleRight.setBackground(new java.awt.Color(196, 181, 129));
        btnSingleRight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSingleRight.setForeground(new java.awt.Color(0, 51, 51));
        btnSingleRight.setText("Add");
        btnSingleRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingleRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSingleRight, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSingleRight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(196, 181, 129));
        jLabel2.setText("Selected Incredient");

        jListTwo.setBackground(new java.awt.Color(196, 181, 129));
        jListTwo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jListTwo.setForeground(new java.awt.Color(0, 51, 51));
        jScrollPane2.setViewportView(jListTwo);

        jButton3.setBackground(new java.awt.Color(196, 181, 129));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(196, 181, 129));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Empty List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(93, 93, 93))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        userid.setForeground(new java.awt.Color(196, 181, 129));
        userid.setText("Id");

        username.setForeground(new java.awt.Color(196, 181, 129));
        username.setText("jLabel4");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(recipiefound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gotorecipies)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(backbutton)
                        .addGap(37, 37, 37)
                        .addComponent(userid)
                        .addGap(18, 18, 18)
                        .addComponent(username)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimizeicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeicon)
                        .addGap(24, 24, 24))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeicon)
                    .addComponent(closeicon)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(backbutton))
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(userid)
                                .addComponent(username)))
                        .addGap(27, 27, 27)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipiefound)
                    .addComponent(gotorecipies))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSingleRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingleRightActionPerformed

        JList<String> myList = new JList<String>();
        int itemCount = jListTwo.getModel().getSize();

        String str2 = jListOne.getSelectedValue();
        if (jListOne.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(rootPane, "No Data Selected...");
        } else {
            if (itemCount > 2) {
                JOptionPane.showMessageDialog(this, "you can only add 3 incredient");
            } else {
                int value = jListOne.getSelectedIndex();
                jlistTwoModel.addElement(str2);
                jListTwo.setModel(jlistTwoModel);

                if (jlistOneModel.getSize() != 0) {
                    jlistOneModel.removeElementAt(value);
                }
                jListOne.setModel(jlistOneModel);
            }
        }
    }//GEN-LAST:event_btnSingleRightActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        // Moving Data to Left or bac to Jlist One:
        String str2 = jListTwo.getSelectedValue();
        if (jListTwo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(rootPane, "No Data Selected...", "Oops...", 1);
        } else {
//Add Value to JList One
            int value = jListTwo.getSelectedIndex();
            jlistOneModel.addElement(str2);
            jListOne.setModel(jlistOneModel);
//Remove Element from JList One.
            if (jlistTwoModel.getSize() != 0) {
                jlistTwoModel.removeElementAt(value);
            }
            jListTwo.setModel(jlistTwoModel);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JList<String> myList = new JList<String>();
        int itemCount = jListTwo.getModel().getSize();

        if (itemCount == 0) {
            JOptionPane.showMessageDialog(rootPane, "List is empty", "Oops...", 1);
        } else {
            DefaultListModel<String> jListOneModel = (DefaultListModel<String>) jListOne.getModel();
            DefaultListModel<String> jListTwoModel = (DefaultListModel<String>) jListTwo.getModel();

            int size1 = jListTwoModel.getSize();

            for (int i = 0; i < size1; i++) {
                jListOneModel.addElement(jListTwoModel.getElementAt(i));
            }
            jListTwoModel.removeAllElements();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
        JList<String> myList = new JList<String>();
        int itemCount = jListTwo.getModel().getSize();

        int total = 3;
        int remaining = total - itemCount;

        if (itemCount < 3) {
            JOptionPane.showMessageDialog(this, "please select " + remaining + " ingredient to perform search");
        } else {
            String firstItem = (String) jListTwo.getModel().getElementAt(0);
            String secondItem = (String) jListTwo.getModel().getElementAt(1);
            String thirdItem = (String) jListTwo.getModel().getElementAt(2);

            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null;

            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://" + databasepath);

                String query = "SELECT COUNT(*) FROM recipes WHERE Ingredient1 IN ('" + firstItem + "', '" + secondItem + "', '" + thirdItem + "') AND Ingredient2 IN ('" + firstItem + "', '" + secondItem + "', '" + thirdItem + "') AND Ingredient3 IN ('" + firstItem + "', '" + secondItem + "', '" + thirdItem + "')";

                pst = con.prepareStatement(query);
                rs = pst.executeQuery();
                int count = 0;
                if (rs.next()) {
                    count = rs.getInt(1);
                    recipiefound.setText(count + " recipes found based on your ingredients.");
                    if (count > 0) {
                        gotorecipies.setText("Show Recipies List.");

                    } else if (count == 0) {
                        gotorecipies.setText("");
                    }

                    // System.out.println(recipiename);
                } else {
                    JOptionPane.showMessageDialog(this, "unSuccessful");

                }

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void gotorecipiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotorecipiesMouseClicked
        // TODO add your handling code here:

        String name = username.getText();
        String id = userid.getText();

        String firstItem = (String) jListTwo.getModel().getElementAt(0);
        String secondItem = (String) jListTwo.getModel().getElementAt(1);
        String thirdItem = (String) jListTwo.getModel().getElementAt(2);

        userrecipielist ul = new userrecipielist(firstItem, secondItem, thirdItem, name, id);

        ul.show();
        dispose();
    }//GEN-LAST:event_gotorecipiesMouseClicked

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backbuttonMouseClicked

    private void minimizeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeiconMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeiconMouseClicked

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeiconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchfilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchfilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchfilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchfilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchfilter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbutton;
    private javax.swing.JButton btnSingleRight;
    private javax.swing.JLabel closeicon;
    private javax.swing.JLabel gotorecipies;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListOne;
    private javax.swing.JList<String> jListTwo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel minimizeicon;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound2;
    private Clases.PanelRound panelRound3;
    private javax.swing.JLabel recipiefound;
    private javax.swing.JButton searchbutton;
    private javax.swing.JLabel userid;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
