/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Atif Jalal
 */
public class Signup extends javax.swing.JFrame {

    String databasepath = "Database.accdb";

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("User Sign up");
        passnotmatch.setText("");
        useralreadyexist.setText("");
        closeicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
        minimizeicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
        backbutton.setCursor(new Cursor(Cursor.HAND_CURSOR));
       this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        inputPassword.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }
        });
        inputConfirmPassword.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }
        });
        inputphonenumber.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }
        });
        enteruserusername.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                passnotmatch.setText("");
                useralreadyexist.setText("");
            }
        });
        emailaddress.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                
                useralreadyexist.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
               
                useralreadyexist.setText("");
            }
        });

        signupbutton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        loginlabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        panelRound2 = new Clases.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        useralreadyexist = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailaddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        passnotmatch = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputConfirmPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        inputphonenumber = new javax.swing.JTextField();
        securityquestion = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        signupbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        loginlabel = new javax.swing.JLabel();
        securityanswer = new javax.swing.JTextField();
        enteruserusername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        minimizeicon = new javax.swing.JLabel();
        closeicon = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(196, 181, 129));
        jLabel1.setText("Sign Up");

        jLabel2.setBackground(new java.awt.Color(196, 181, 129));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(196, 181, 129));
        jLabel2.setText("Full Name:");

        useralreadyexist.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        useralreadyexist.setForeground(new java.awt.Color(255, 0, 0));
        useralreadyexist.setText("Username Exist");

        jLabel3.setBackground(new java.awt.Color(196, 181, 129));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(196, 181, 129));
        jLabel3.setText("Email:");

        emailaddress.setBackground(new java.awt.Color(0, 51, 51));
        emailaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailaddress.setForeground(new java.awt.Color(196, 181, 129));
        emailaddress.setBorder(null);

        jLabel4.setBackground(new java.awt.Color(196, 181, 129));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(196, 181, 129));
        jLabel4.setText("Password:");

        inputPassword.setBackground(new java.awt.Color(0, 51, 51));
        inputPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputPassword.setForeground(new java.awt.Color(196, 181, 129));
        inputPassword.setBorder(null);

        passnotmatch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passnotmatch.setForeground(new java.awt.Color(255, 0, 0));
        passnotmatch.setText("Password does not match");

        jLabel5.setBackground(new java.awt.Color(196, 181, 129));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(196, 181, 129));
        jLabel5.setText("Confirm Password");

        inputConfirmPassword.setBackground(new java.awt.Color(0, 51, 51));
        inputConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputConfirmPassword.setForeground(new java.awt.Color(196, 181, 129));
        inputConfirmPassword.setBorder(null);
        inputConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConfirmPasswordActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(196, 181, 129));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(196, 181, 129));
        jLabel6.setText("Phone:");

        inputphonenumber.setBackground(new java.awt.Color(0, 51, 51));
        inputphonenumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputphonenumber.setForeground(new java.awt.Color(196, 181, 129));
        inputphonenumber.setBorder(null);

        securityquestion.setForeground(new java.awt.Color(102, 102, 102));
        securityquestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "what was your first car?", "what is your secret number?", "what is your favorite food?", "what is your lucky color?", "what is your dream place?" }));

        jLabel12.setBackground(new java.awt.Color(196, 181, 129));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(196, 181, 129));
        jLabel12.setText("Answer of security Question");

        jLabel11.setBackground(new java.awt.Color(196, 181, 129));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(196, 181, 129));
        jLabel11.setText("Choose your security Question");
        jLabel11.setToolTipText("");

        signupbutton.setBackground(new java.awt.Color(196, 181, 129));
        signupbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signupbutton.setForeground(new java.awt.Color(0, 51, 51));
        signupbutton.setText("Sign Up");
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(196, 181, 129));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(196, 181, 129));
        jLabel7.setText("Already have an account?");

        loginlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginlabel.setForeground(new java.awt.Color(51, 153, 255));
        loginlabel.setText("login");
        loginlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginlabelMouseClicked(evt);
            }
        });

        securityanswer.setBackground(new java.awt.Color(0, 51, 51));
        securityanswer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        securityanswer.setForeground(new java.awt.Color(196, 181, 129));
        securityanswer.setBorder(null);

        enteruserusername.setBackground(new java.awt.Color(0, 51, 51));
        enteruserusername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enteruserusername.setForeground(new java.awt.Color(196, 181, 129));
        enteruserusername.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(196, 181, 129));
        jSeparator1.setForeground(new java.awt.Color(196, 181, 129));
        jSeparator1.setToolTipText("");

        jSeparator2.setBackground(new java.awt.Color(196, 181, 129));
        jSeparator2.setForeground(new java.awt.Color(196, 181, 129));
        jSeparator2.setToolTipText("");

        jSeparator3.setBackground(new java.awt.Color(196, 181, 129));
        jSeparator3.setForeground(new java.awt.Color(196, 181, 129));
        jSeparator3.setToolTipText("");

        jSeparator5.setBackground(new java.awt.Color(196, 181, 129));
        jSeparator5.setForeground(new java.awt.Color(196, 181, 129));
        jSeparator5.setToolTipText("");

        jSeparator6.setBackground(new java.awt.Color(196, 181, 129));
        jSeparator6.setForeground(new java.awt.Color(196, 181, 129));
        jSeparator6.setToolTipText("");

        minimizeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/minimizegold.png"))); // NOI18N
        minimizeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeiconMouseClicked(evt);
            }
        });

        closeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/closegold.png"))); // NOI18N
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
        });

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/backbuttongold.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(196, 181, 129));
        jSeparator4.setForeground(new java.awt.Color(196, 181, 129));
        jSeparator4.setToolTipText("");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passnotmatch))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(loginlabel))
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(backbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(minimizeicon)
                                .addGap(3, 3, 3)))
                        .addComponent(closeicon))
                    .addComponent(enteruserusername)
                    .addComponent(jSeparator1)
                    .addComponent(emailaddress)
                    .addComponent(jSeparator2)
                    .addComponent(inputPassword)
                    .addComponent(inputConfirmPassword)
                    .addComponent(jSeparator3)
                    .addComponent(inputphonenumber)
                    .addComponent(jSeparator5)
                    .addComponent(securityquestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(securityanswer)
                    .addComponent(jSeparator6)
                    .addComponent(signupbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(useralreadyexist)
                        .addGap(8, 8, 8)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeicon)
                    .addComponent(minimizeicon)
                    .addComponent(jLabel1)
                    .addComponent(backbutton))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enteruserusername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(useralreadyexist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passnotmatch)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(loginlabel))
                .addGap(30, 30, 30))
        );

        getContentPane().add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 330, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/signupimage.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String encryptPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(password.getBytes());
            byte[] digest = md.digest();
            StringBuilder sb = new StringBuilder();
            for (byte b : digest) {
                sb.append(String.format("%02x", b & 0xff));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
            return null;
        }
    }
    
    
    
    
    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        // TODO add your handling code here:
        String username = enteruserusername.getText();
        String email = emailaddress.getText();
        String firstpassword = new String(inputPassword.getPassword());
        String secondpassword = new String(inputConfirmPassword.getPassword());
        int passlength = secondpassword.length();
        String phonenumber = inputphonenumber.getText();
        String usertypedefault = "user";
        String SecQuestion=(String) securityquestion.getSelectedItem();
        String Secans=securityanswer.getText().toLowerCase();
        

        if (username.isEmpty() || email.isEmpty() || firstpassword.isEmpty() || secondpassword.isEmpty() || phonenumber.isEmpty() || Secans.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill up form Properly");
        } else if (passlength < 8) {
            JOptionPane.showMessageDialog(this, "password should be more than 8 chracters");
        }
        else if (passlength > 16) {
            JOptionPane.showMessageDialog(this, "password should be less than 16 chracters");
        }
        else {

            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null;

            try {

                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://" + databasepath);
                String query1 = "SELECT * FROM user WHERE Email = '" + email + "'";

                pst = con.prepareStatement(query1);
                rs = pst.executeQuery();

                if (rs.next()) {
                    useralreadyexist.setText("Email already Used.");
                    emailaddress.setText("");

                } else {
                    if (!firstpassword.equals(secondpassword)) {
                        passnotmatch.setText("Password does not match");
                        inputPassword.setText("");
                        inputConfirmPassword.setText("");
                    } else if (firstpassword.equals(secondpassword)) {
                        
                        String encryptedPassword = encryptPassword(firstpassword);
                        
                        passnotmatch.setText("");
                        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                        con = DriverManager.getConnection("jdbc:ucanaccess://" + databasepath);
                        String query = "insert into user(Username, Email, Password, PhoneNumber , usertype,SecurityQuestion,SecurityAnswer) values (?, ?, ?, ?, ?, ?, ?)";
                        pst = con.prepareStatement(query);
                        pst.setString(1, username);
                        pst.setString(2, email);
                        pst.setString(3, encryptedPassword);
                        pst.setString(4, phonenumber);
                        pst.setString(5, usertypedefault);
                        pst.setString(6, SecQuestion);
                        pst.setString(7, Secans);
                        
                        
                        
                        int rows = pst.executeUpdate();
                        if (rows > 0) {
                            JOptionPane.showMessageDialog(this, "SignUp Successful");
                            LoginForm lgf = new LoginForm();
                            lgf.show();
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "SignUp failed");
                        }
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }//GEN-LAST:event_signupbuttonActionPerformed

    private void loginlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlabelMouseClicked
        // TODO add your handling code here:
        LoginForm lf = new LoginForm();;
        lf.show();
        dispose();
    }//GEN-LAST:event_loginlabelMouseClicked

    private void inputConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConfirmPasswordActionPerformed

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeiconMouseClicked

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
        LoginForm lf = new LoginForm();
        lf.show();
        dispose();
    }//GEN-LAST:event_backbuttonMouseClicked

    private void minimizeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeiconMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeiconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbutton;
    private javax.swing.JLabel closeicon;
    private javax.swing.JTextField emailaddress;
    private javax.swing.JTextField enteruserusername;
    private javax.swing.JPasswordField inputConfirmPassword;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputphonenumber;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel loginlabel;
    private javax.swing.JLabel minimizeicon;
    private Clases.PanelRound panelRound2;
    private javax.swing.JLabel passnotmatch;
    private javax.swing.JTextField securityanswer;
    private javax.swing.JComboBox securityquestion;
    private javax.swing.JButton signupbutton;
    private javax.swing.JLabel useralreadyexist;
    // End of variables declaration//GEN-END:variables
}
